#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N join_paired_ends
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

time join_paired_ends.py \
-m SeqPrep \
-b ~/2018/raw_data/Index.fastq.gz \
-f ~/2018/raw_data/Read1.fastq.gz \
-r ~/2018/raw_data/Read2.fastq.gz \
-o ~/2018/raw_data/seq_prep_joined \

source deactivate

