#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N make_otu_table
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

time make_otu_table.py \
-i ~/2018/clos_ref_otus/uclust_ref_picked_otus/seqs_otus.txt \
-t ~/2018/taxonomy_res/rep_set_tax_assignments.txt \
-o ~/2018/clos_ref_otus/make_otu_table/otu_table_tax.biom 


source deactivate

