#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N OTU_picking
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

time pick_closed_reference_otus.py \
-i ~/2018/split_data_paired/seqs.fna \
-o ~/2018/silva_otus \
-r ~/silva_db/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-a \
-O 8 \

source deactivate

