#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N procrust_analysis
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

time transform_coordinate_matrices.py \
-i ~/2018/core_div_output/bdiv_even637/unweighted_unifrac_pc.txt,~/2018/core_div_output/bdiv_even637/weighted_unifrac_pc.txt \
-o ~/2018/procrust_out/ \
-r 100 \

echo "first script executed successfully, starting the second"

time make_emperor.py \
-i ~/2018/procrust_out/ \
-o ~/2018/procrust_out/emperor/ \
-c \
-m ~/2018/map.tsv

source deactivate

