#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24
#PBS -N split_fastq
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1


time split_libraries_fastq.py \
-m ~/2018/raw_data/map.tsv \
-i ~/2018/raw_data/seq_prep_joined/seqprep_assembled.fastq.gz \
-b ~/2018/raw_data/seq_prep_joined/seqprep_assembled.fastq_barcodes.fastq.gz \
-o ~/2018/split_library_paired \
-q 19 \
--barcode_type 12
